version: '3.7'
services:
  judger:
    container_name: saboj_judger
    image: vnoj/judge-tiervnoj:latest
    volumes:
      - ./problems/:/problems/
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    command: run -p 9999 -c /problems/judge.yml "localhost" "vnoi" "51kC55s5QnS8aCaQUYAoxcQxJzfQHxkdzah7XrPLsdulXpzsa5c7QGxeGE8+67jTm9Ep4dIu25TOozyr2jNVwGhTg6UIRFivSgvN"
    network_mode: host
  db:
    container_name: dmoj_mysql
    image: mariadb
    restart: always
    volumes:
      - ./database/:/var/lib/mysql/
    env_file: [environment/mysql.env, environment/mysql-admin.env]
    networks: [db]
  redis:
    container_name: dmoj_redis
    image: redis:alpine
    restart: always
    networks: [site, multi-domain]
  texoid:
    build:
      context: .
      dockerfile: ./texoid/Dockerfile
    image: ninjaclasher/dmoj-texoid
    init: true
    restart: unless-stopped
    networks: [site, multi-domain]
  pdfoid:
    build:
      context: .
      dockerfile: ./pdfoid/Dockerfile
    image: ninjaclasher/dmoj-pdfoid
    init: true
    restart: unless-stopped
    networks: [site, multi-domain]
    cap_add:
      - SYS_ADMIN
  mathoid:
    build:
      context: .
      dockerfile: ./mathoid/Dockerfile
    image: ninjaclasher/dmoj-mathoid
    init: true
    restart: unless-stopped
    volumes:
      - ./mathoid/config.yaml:/node_modules/mathoid/config.yaml
    networks: [site, multi-domain]
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: ninjaclasher/dmoj-base
    network_mode: none
  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    image: ninjaclasher/dmoj-site
    init: true
    restart: unless-stopped
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./media/:/media/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db, multi-domain]
    depends_on: [base, db, redis]
  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: ninjaclasher/dmoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db, multi-domain]
    depends_on: [base, db, redis]
  bridged:
    container_name: dmoj_bridged
    build:
      context: .
      dockerfile: ./bridged/Dockerfile
    image: ninjaclasher/dmoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - pdfcache:/pdfcache/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db, multi-domain]
    ports:
      - 9999:9999
    depends_on: [base, db, redis]
  wsevent:
    build:
      context: .
      dockerfile: ./wsevent/Dockerfile
    image: ninjaclasher/dmoj-wsevent
    init: true
    restart: unless-stopped
    volumes:
      - ./repo/:/app/site/
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, multi-domain]
  nginx:
    container_name: dmoj_nginx
    image: nginx:alpine
    restart: always
    expose:
      - 80
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx, multi-domain]
    depends_on: [site, wsevent]    
networks:
  site:
  db:
  nginx:
  multi-domain:
    external: true
    name: multi-domain
volumes:
  assets:
  pdfcache:
  datacache:
  cache:
